### PR TITLE
Update upstream to 4.3.1

### PR DESCRIPTION
**Pull request by tamird**
Reapplied a69d4e23b715271498914f6b9e302a89177fb519 on top because it hasn't made it into a release yet.

@marc @petermattis @bdarnell

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

**Comment by RaduBerinde** [comment]
I tried checking out this PR in `c-rocksdb` and running a test in `cockroach` (I was investigating #5855 and wanted to see if it works with the newer rocksdb). I get this:
`/tmp/go-build175573054/github.com/cockroachdb/cockroach/sql/_test/sql.test: symbol lookup error: /tmp/go-build175573054/github.com/cockroachdb/cockroach/sql/_test/sql.test: undefined symbol: _ZTVN7rocksdb14PosixDirectoryE`
I did do a `make clean` before. Not sure if I should have done something else.

**Comment by tamird** [comment]
Yeah, I see that locally as well. Will investigate tomorrow.

**Comment by petermattis** [comment]
As discovered with @tamird, we need to add `-DROCKSDB_LIB_IO_POSIX` to `cgo_flags.go`.

**Comment by tamird** [comment]
Updated all the flags using `build_tools/build_detect_platform`, and added instructions to import.sh

**Comment by petermattis** [comment]
Did you intend to get rid of `-DNDEBUG` and `-DLZ4`? The latter seems ok as we're not using lz4 compression with rocksdb, but the former is more problematic as it turns on all sorts of debugging code.

**Comment by tamird** [comment]
Oops, I sure didn't. Reverted both.

**Comment by tamird** [comment]
With @petermattis' help, this is good to go. Merging.

**Pull request merged**
