### PR TITLE
Enable assertions in race builds

### PR DESCRIPTION
**Pull request by bdarnell**
See cockroachdb/cockroach#9168

@cockroachdb/stability

### CODE REVIEW

**Comment by tbg** [comment]
LGTM

**Comment by tamird** [comment]
We need to revert 0cc8a3dd0597a9f92cb0a8a3b60154d09d3cb35a first, right?

**Comment by petermattis** [comment]
LGTM

**Comment by bdarnell** [comment]
The parent of this commit is 4.8, so we don't need to revert. We can point the glockfile to this commit (pre-merge) for assertions-enabled 4.8, and the merge of this commit for assertions-enabled 4.9.

**Comment by tamird** [comment]
Neat.

**Pull request merged**
