### PR TITLE
Include TOOLS_LIB_SOURCES in build

### PR DESCRIPTION
**Pull request by bdarnell**
This lets us build a customized version of the `ldb` command.

### CODE REVIEW

**Comment by bdarnell** [comment]
This branch is based on 4.11. How aggressive do we want to be about rolling out 5.0? Should I just rebase this on top of 5.0 or might we want this tool sooner than that? @petermattis

**Comment by petermattis** [comment]
I want to see 5.0 running on test clusters for a while before it ends up in a beta. Are you going to build a standalone tool, or bake something into the `cockroach` binary? If it is a standalone tool, I think it is fine to rebase this on top of 5.0.

**Comment by bdarnell** [comment]
It's built into `cockroach`; see cockroachdb/cockroach#12914. It's also low priority since this tool hasn't proven to be very useful so far.

**Comment by bdarnell** [comment]
Rebased onto 5.0

**Review by petermattis — APPROVED** [review]
LGTM

**Pull request merged**
