### PR TITLE
Fix index seeking in BlockTableReader::PrefixMayMatch.

### PR DESCRIPTION
**Pull request by petermattis**
See facebook/rocksdb#923.
See cockroachdb/cockroach#3624.

### CODE REVIEW

**Comment by petermattis** [comment]
@tschottdorf, @tamird

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
LGTM

**Comment by petermattis** [comment]
There is some upstream discussion about a possibly simpler solution, but I'm going to merge this for now. When the upstream change is merged we can back port.

**Pull request merged**
