### PR TITLE
Use prefix_same_as_start to avoid iteration in FindNextUserEntryInternal.

### PR DESCRIPTION
**Pull request by petermattis**
This avoids excessive iteration in tombstone fields.

### CODE REVIEW

**Comment by petermattis** [comment]
This is a cherry-pick of https://github.com/facebook/rocksdb/pull/1102.

**Comment by tamird** [comment]
LGTM. Can you add a patch and hook it up to import.sh? Otherwise we might forget to reapply this when we update rocksdb (since their release cycle lags, and this change won't be in the next 1 or 2 releases).

**Comment by petermattis** [comment]
Good idea about the patches. Done. Verified by running `./import.sh` and nothing changed except `build_version.cc`.

**Comment by tamird** [comment]
Nice, thanks for backfilling that other guy, too. Fire away.

**Pull request merged**
